SET PATH=D:\Keil_v5\ARM\ARMCC\Bin;C:\ProgramData\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\Program Files (x86)\Bitvise SSH Client;C:\Program Files\Java\jdk1.8.0_60\bin;C:\Program Files\Java\jdk1.8.0_60\jre\bin;D:\Program Files\MATLAB\R2013b\runtime\win64;D:\Program Files\MATLAB\R2013b\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;D:\Program Files (x86)\nodejs\;D:\Program Files\Git\cmd;C:\Program Files (x86)\Autodesk\Backburner\;C:\Users\HUBIN\AppData\Roaming\npm;C:\Users\HUBIN\AppData\Local\atom\bin
SET CPU_TYPE=STM32F103C8
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=Lab3-BicycleStopwatch
SET CPU_CLOCK=0x007A1200
"D:\Keil_v5\ARM\ARMCC\Bin\ArmAsm" --Via "lab3-bicyclestopwatch\startup_stm32f103xb._ia"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_dma.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_cortex.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_tim_ex.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_gpio.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_flash.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_rcc_ex.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_flash_ex.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_uart.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_rcc.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_tim.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_pwr.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\main.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_it.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\stm32f1xx_hal_msp.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmCC" --Via "lab3-bicyclestopwatch\system_stm32f1xx.__i"
"D:\Keil_v5\ARM\ARMCC\Bin\ArmLink" --Via "Lab3-BicycleStopwatch\Lab3-BicycleStopwatch.lnp"
